version: '3.5'

services:
  webssh:
    image: billchurch/webssh2
    ports:
      - "2222:2222"
    volumes:
      - ./config.json:/usr/src/config.json
  app:
    build: .
    ports:
      - "2223:2223"
    volumes:
      - ./.ssh:/app/.ssh
      - ./highscore.json:/app/highscore.json
